FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
COPY . .
CMD ["python3", "./app.py"]